services:
  app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile

    volumes:
      - ../..:/workspaces:cached

    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity

    depends_on:
    - mysql

  mysql:
    image: mysql/mysql-server:8.0
    restart: unless-stopped
    environment:
        MYSQL_ALLOW_EMPTY_PASSWORD: 'true'
        MYSQL_ROOT_HOST: "%"
    volumes:
    - mysql-data:/var/lib/mysql
    networks:
    - default

volumes:
  mysql-data:
